### PR TITLE
Upgrade Spreadsheet Widget to Sheets API v4

### PR DESCRIPTION
**Pull request by donnapep**
* Widget has to fetch the sheet name from the API since settings does not save this information, only the tab ID.
* Moved range integration tests into main integration tests.
* [Presentation](http://goo.gl/wdFDnO)

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Since the sheet tab id isn't relevant anymore with latest release of `rise-google-sheet`, I think it would be better to revise the settings to save the sheet name instead of tabid to `additionalParams` so that we don't have to fetch the sheet name from the API in the widget. Thoughts?

**Comment by donnapep** [comment]
@stulees That would be ideal. But that means we would break the Widget for users that are currently using it. Unless we don't care about being backwards compatible because we're in early preview?

**Comment by stulees** [comment]
@donnapep Could we maintain passing tabid from settings for backwards compatibility but additionally pass the sheet name?

**Comment by donnapep** [comment]
@stulees We could, but then we're making the code even more complex. Why don't I create a card and we can discuss over there? Would be good to have Alan weigh in.

**Comment by donnapep** [comment]
@stulees Can this one still be approved? I don't think the decision that is pending on the Trello card will have any effect on this PR.

**Comment by stulees** [comment]
@donnapep 👍 One thing I did notice in your presentation is the mention of the missing GSAP CSSPlugin in the console - http://www.screencast.com/t/aYoCV4JX . Not sure if that is to be expected.

**Comment by donnapep** [comment]
@stulees That's been there awhile. I'm hoping integration of the scrolling component will fix it.

**Pull request merged**
