### PR TITLE
Implemented refresh on the widget side

### PR DESCRIPTION
**Pull request by rodrigopavezi**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good 👍 cheers

**Comment by donnapep** [comment]
@rodrigopavezi Please review last commit. Thx!

**Comment by rodrigopavezi** [comment]
@donnapep looks good 👍 cheers

**Pull request merged**
