### PR TITLE
Feature/spreadsheet key

### PR DESCRIPTION
**Pull request by donnapep**
* Add support for selecting spreadsheet by key.
* Add new `selection` setting to distinguish between when a file is selected using Google Drive vs. entering a spreadsheet key.
* Renamed `docUrl` setting to `url` to be consistent with other Widgets.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep I don't think the doc name and open spreadsheet button should initially be showing when opening the settings - http://www.screencast.com/t/KcFRnWVu

**Comment by donnapep** [comment]
@stulees Fixed that and also moved the validation check to `fileId`. Thx.

**Comment by stulees** [comment]
@donnapep 👍

**Pull request merged**
