### PR TITLE
[Fix] Ensuring table data gets refreshed when content can scroll but not auto scroll

### PR DESCRIPTION
**Pull request by stulees**
- Adding in conditional check that the auto scroll setting is "none" to immediately update the table
- Adding new integration test coverage and improving previous tests
- Updating dependencies

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by alanclayton** [comment]
@stulees given @donnapep is out could @rodrigopavezi review?

**Comment by stulees** [comment]
@rodrigopavezi This PR is a fix for the escalated issue #131 . Can you review, thanks!

**Comment by rodrigopavezi** [comment]
@stulees code looks good. Is there a way to play with this version of the widget? I mean is it staged somewhere? cheers

**Comment by stulees** [comment]
@rodrigopavezi I flagged you on the Trello card to provide info regarding validating. Can I consider the PR a + 1 then?

**Comment by rodrigopavezi** [comment]
@stulees yeap!! :+1: cheers

**Pull request merged**
