### PR TITLE
Fix in conditional logic of content scrollPlay function

### PR DESCRIPTION
**Pull request by stulees**
- The conditional check of `!_isScrolling` within the only `if` statement is resulting in `_startPUDTimer` sometimes being called when it shouldn't be if the content is scrollable
- Ensuring the conditional check of `isScrolling` is done within the conditional block of the content being scrollable

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Given that `scrollPlay` is public, can we figure out a way to test this? For example, using Sinon to listen for the `play` function of `$scroll` being called. Or in the `else` case, checking to see that the timer was set by advancing the clock and seeing if it fires. Even if this requires refactoring or making private members public, I think we need to bite the bullet and do it.

**Comment by stulees** [comment]
@donnapep We spoke, I've now reinforced the same tests already existing to test for calls made to the autoScroll `play()` which gives assurance on whether a call to `_startPUDTimer()` happens or not. Please review again, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
