### PR TITLE
Fixed issue 251 by removing the border from the.fixedDataTableCellLay…

### PR DESCRIPTION
**Pull request by rodrigopavezi**
…out_main class

@stulees you can see the issue on this presentation 
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=8e04c4d6-4ea2-4b47-ae1d-77ad771a941e?cid=d0b5f2b2-3547-4805-93ee-8b11aea3d658

I tried to apply border-collapse:collapse; but it did not worked because the border styling is not defined on the cell class where it has display: table-cell;

here is a sample how to make it work with border-collapse: collapse http://jsfiddle.net/R8eCr/5/

This will not work because fix data table declare the border styles in another parent class fixedDataTableCellLayout_main

So I am fixing it by adding border: none when the border settings are not present. 

This is the presentation with the fix http://rva.risevision.com/#/PRESENTATION_MANAGE/id=4a004054-2da8-49d7-87b3-925e19ccf2bb?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

Please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Curious, have you validated that everything works correctly in all border scenarios? No Rows/No Columns, Show Rows/No Columns, No Rows/Show Columns, and Show Rows/Show Columns? Also, can you validate everything looks correct when you don't use first row as header?

**Comment by rodrigopavezi** [comment]
@stulees yeap, all scenarios were validated. Did you seen any inconsistence? cheers

**Comment by stulees** [comment]
@rodrigopavezi No inconsistencies, looks good. 👍

**Comment by stulees** [comment]
@rodrigopavezi Actually, to confirm, there is no opportunity for test coverage?

**Comment by rodrigopavezi** [comment]
@stulees good point, test added. please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi 👍

**Pull request merged**
