### PR TITLE
Attempted to use autoScroll. Problems with jquery and webpack

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep this is what I got so far. cheers

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@donnapep @stulees please review. cheers

**Comment by donnapep** [comment]
@rodrigopavezi This is looking good! The autoscroll component needs to start playing when Viewer tells it to play, and pause when Viewer tells it to pause. Also, this change needs some test coverage.

**Comment by donnapep** [comment]
@rodrigopavezi At a minimum, I think we could add unit tests for the Scroll component similar to what we have for Table and TableHeader.

**Comment by rodrigopavezi** [comment]
@donnapep I have made the changes to call done and pause. I have also fixed tests and add some tests for scrolling. I could not find a way to test the jquery part of it. Please let me know if you know of a way. cheers

**Comment by donnapep** [comment]
👍

**Pull request merged**
