### PR TITLE
Implemented the api key validation

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@stulees please review. cheers

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@stulees presentation here: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=d9349650-2054-4f0d-a731-f0e58b26e089?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by stulees** [comment]
@rodrigopavezi Looks good. One thing though is if you delete the chosen spreadsheet, API key entry remains visible - http://www.screencast.com/t/eKQWtL5tg . I'm also thinking we should hide everything spreadsheet related unless a spreadsheet is chosen (worksheet selection, first row as header, etc). Thoughts?

**Comment by rodrigopavezi** [comment]
@stulees good catch, I have changed that and also added tests. Good point we should hide other stuff too. I will add a card for that. Another thing I noticed is that we call getWorkSheets for everything inserted on the file key field. That is because we call it using a watch. We should instead implement it on a ng-blur. I will add a card for that too as we don't want to be expending api calls unnecessarily. cheers

**Comment by stulees** [comment]
@rodrigopavezi 👍 Agreed about getWorkSheets being called from key entry of file key field, thanks!

**Comment by rodrigopavezi** [comment]
@stulees changed it to disable the api key field instead of hiding it as per @alanclayton request. Please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good 👍

**Pull request merged**
