### PR TITLE
Show error message when spreadsheet not published [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Display a waiting message until a response/error has been received from `rise-google-sheet` instance
- Handling `rise-google-sheet-error` and displaying message when it occurs
- Including widget-common as node dependency to allow for requiring Message CSS in app
- Test coverage

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍 cheers

**Comment by donnapep** [comment]
@stulees Shouldn't showing and hiding the message be taken care of by the `render` function?

**Comment by donnapep** [comment]
@stulees Or perhaps Message should even be its own component?

**Comment by donnapep** [comment]
@stulees 👍  We talked and are going to deploy but revisit to refactor as a separate component later.

**Pull request merged**
