### PR TITLE
Removing "Auto" from Header Row selection

### PR DESCRIPTION
**Pull request by stulees**
- Pulling in latest Google Spreadsheet Controls component that removes the "Auto" selection for Header Row and defaults on "1"
- Added "bower-clean-install" task to gulp file and added dependencies for it to `package.json`
- Gulp file updated to ensure "prod" version is built for `dist/`
- Revised e2e tests
- Removed help button from settings HTML

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep This applies the change from Google Spreadsheet Controls where it has removed the "Auto" selection from the Header Row. It pertains to issue https://github.com/Rise-Vision/widget-google-spreadsheet/issues/119 that you already know of. 

It will not break an existing presentation, however, in their previously saved Settings page, if they had saved "Auto", then a blank selection will initially show and they will have to choose a new one. Please review, thanks.

**Comment by donnapep** [comment]
:+1:

**Comment by donnapep** [comment]
@stulees Forgot to ask, but are Alan and Support aware of and okay with a blank Display for Auto?

**Comment by stulees** [comment]
@donnapep Just been given the go ahead from Alan and Support for being okay with a blank selection, thanks.

**Pull request merged**
