### PR TITLE
Fix for issue regarding worksheet selector

### PR DESCRIPTION
**Pull request by stulees**
- Rebuilding to include fix from `google-spreadsheet-controls` component
- Fixing issue with CCI build

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, this fixes issue #138 . Presentation to validate - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=a0fc566e-1f5c-4201-b7d5-1b99a8e92d35?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by donnapep** [comment]
@stulees So you didn't have to do a version bump on `google-spreadsheet-controls`? Did we want to add a version?

**Comment by stulees** [comment]
@donnapep It doesn't have any releases and the widget just picks up the latest. We can change to use releases in our Spreadsheet epic.

**Comment by donnapep** [comment]
@stulees Ah, OK. 👍

**Pull request merged**
