### PR TITLE
[Fix] Ensuring number value maintains decimals when of text format

### PR DESCRIPTION
**Pull request by stulees**
- Ensuring to check if `column.decimals` has a value to either apply `toFixed()` or not

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by stulees** [comment]
@donnapep FYI this is a fix for scenario 2 of issue #117 . I have determined scenario 1 is a limitation of the Visualization API when mixed formats are used. It does not provide the cell value when the format of the cell is not of the determined column format.

**Comment by donnapep** [comment]
@stulees Is it possible to add a test for this?

**Comment by stulees** [comment]
@donnapep Test added, thanks

**Comment by donnapep** [comment]
@stulees Awesome! Thx. :+1:

**Pull request merged**
