### PR TITLE
Updating font-setting version for custom font name fix [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- `babel-runtime` now required for `babel-preset-es2015`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by donnapep** [comment]
@stulees Can you clarify how you determined that `babel-runtime` is now required?

**Comment by stulees** [comment]
@donnapep When I deleted node_modules folder and did an npm install it was failing stating babel-preset-es2015 was requiring babel-runtime and it couldn't be found.

**Comment by donnapep** [comment]
@stulees OK, thx. You must be running a different version of Node because mine installed fine. 👍

**Comment by stulees** [comment]
@donnapep Hm, I make sure to use the version of node that the project circle.yml file states, so for this I was using 4.4.3. Were you using 6.6.0?

**Comment by donnapep** [comment]
@stulees I just tried running against Node v4.4.3 and it installed fine. Must be something else.

**Comment by stulees** [comment]
@donnapep So I hid a bit of short term memory loss. It wasn't a problem with the npm install, it was occurring when running a gulp build. However, I've since removed the dependency and done a fresh npm install and gulp build and it's fine. Not sure what was going on yesterday but not worth looking into further. Please review last commit, thanks.

**Comment by donnapep** [comment]
@stulees Oh yeah, inexplicable 💩  is the best. 👍

**Pull request merged**
