### PR TITLE
Migrate message integration tests to unit tests

### PR DESCRIPTION
**Pull request by donnapep**
* Migrate message integration tests to unit tests.
* Create `MessageContainer` component.
* Move rise-google-sheet event handlers to own function since Chrome was complaining about missing parameter to `sheet.removeEventListener`.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep To clarify, is it not possible to move all of our integration tests to use Enzyme? I thought this card https://goo.gl/i8sNQN was to do that?

**Comment by donnapep** [comment]
@stulees No, Enzyme is for testing React components. `mainContainer` and `rise-google-sheet` are not React components so we can't use it here. But moving forward we should be diligent about ensuring we test all our React components using Enzyme.

To clarify, we should use Enzyme for testing React and write integration tests for everything else.

**Comment by stulees** [comment]
@donnapep Okay makes sense. Part of the reason the card was created was that I ran into a block in writing a test for messaging that tested the legacy message being shown. This was due to the use of our Common module within the component - https://github.com/Rise-Vision/widget-google-spreadsheet/blob/master/src/widget/components/spreadsheet.jsx#L92 and not being able to stub the `isLegacy` function. I don't see a new test for that in this PR so I'm assuming it's still a problem, can you clarify?

**Comment by donnapep** [comment]
@stulees I didn't investigate that at all as I didn't see it referenced in the existing integration tests, and I didn't think to try it. I really just tried to rewrote what was already there and then of course realized we wouldn't be able to use Enzyme for some of those tests. As such, I think I would consider that particular test out of scope for this particular PR.

**Comment by stulees** [comment]
@donnapep 👍 Fair enough. I think going forward with React code we're going to run into these test coverage blocks when we use imported non-react modules. If we were to port some of this functionality (eg. widget-common Common module) to React utility containers (?), I think we might have more opportunity for improving tests. What do you think?

**Comment by donnapep** [comment]
@stulees I agree that the biggest challenge we have uncovered so far is getting React code to work with non-React code. I think React would be a lot easier for us to use if everything was built with it. Yes, perhaps we could wrap this "legacy" code with React. I wonder how other people handle this and if they've found an optimal solution or if they just rewrite everything.

**Pull request merged**
